name: TikTok to Facebook Auto Upload

on:
  schedule:
    - cron: "0 18 * * *"   # every hour
  workflow_dispatch:      # manual trigger

jobs:
  repost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp

      - name: Run TikTok → Facebook script
        env:
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python tiktok.py
