name: TikTok to Facebook Auto Upload

on:
  schedule:
    - cron: "0 18 * * *"   # runs daily at 6 PM UTC (adjust to your timezone)
  workflow_dispatch:       # manual trigger

jobs:
  repost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp

      # ⬇️ Download previous state (if exists)
      - name: Restore last_video_id
        uses: actions/download-artifact@v4
        with:
          name: last-video
          path: downloads
        continue-on-error: true   # ignore if first run

      - name: Run TikTok → Facebook script
        env:
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python tiktok.py

      # ⬆️ Save state for next run
      - name: Save last_video_id
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: last-video
          path: downloads/last_video_id.txt
